ControllerSettings:
  boundary_conditions:
    minimum_voltage: 0.98  # Minimum voltage at the grid connection point.
    maximum_voltage: 1.02  # Maximum voltage at the grid connection point.
    minimum_temperature: 15  # Minimum temperature in the room.
    maximum_temperature: 30  # Maximum temperature in the room.
  actions:
    p_change_for_voltage: 2000  # Step size [W] for power setpoint adjustment for voltage correction.
    p_change_for_temperature: 2000  # Step size [W] for power setpoint adjustment for temperature correction.
